version: '3'

services:
  db:
    image: mysql:8.2.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
    expose:
      - 3306

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ewano:/var/www/html/wp-content/plugins/ewano
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WP_DEBUG: 'true'
    depends_on:
      - db

volumes:
  db_data:
  wordpress_data: # This is for persisting the wordpress data
